<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'title' => 'ECサイトプラットフォームの新規開発',
                'period' => '6ヶ月〜（7月より）',
                'working_hours' => '9:30-18:30（休憩1h）',
                'workplace' => '大阪府大阪市',
                'display_price' => '650,000円',
                'skills' => 'Python, TypeScript, React, Django, AWS',
                'summary' => '大手小売チェーン向けの次世代ECプラットフォーム開発プロジェクトです。在庫管理システムとの連携や、AIを活用したレコメンデーション機能の実装が主な特徴です。マイクロサービスアーキテクチャを採用し、スケーラビリティの高いシステムを目指します。',
                'head_count' => '2名',
                'monthly_working_hours' => '165時間/月',
                'price' => bindec('10000'), 
                'start' => bindec('1000000'), 
                'area' => bindec('100000000000000000000000000'), 
                'remote' => bindec('10'), 
                'frontend' => bindec('1000000'), 
                'backend' => bindec('10000000'), 
                'framework' => bindec('100000100'), 
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => '製造業向け生産管理システム構築',
                'period' => '9ヶ月〜（1月より）',
                'working_hours' => '9:00-18:00（休憩1h）',
                'workplace' => '愛知県名古屋市',
                'display_price' => '750,000円',
                'skills' => 'Java, Spring, C#, TypeScript, Angular',
                'summary' => '大手製造業向けの生産管理システム構築プロジェクトです。既存の基幹システムとの連携や、IoTデバイスからのリアルタイムデータ収集・分析機能の実装が含まれます。品質管理や工程管理の効率化を図ります。',
                'head_count' => '4名',
                'monthly_working_hours' => '170時間/月',
                'price' => bindec('100000'), 
                'start' => bindec('1'), 
                'area' => bindec('10000000000000000000000'), 
                'remote' => bindec('1'), 
                'frontend' => bindec('1000000'), 
                'backend' => bindec('100100'), 
                'framework' => bindec('10000000001'), 
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => 'クラウドネイティブアプリケーション開発',
                'period' => '8ヶ月〜（10月より）',
                'working_hours' => '10:00-19:00（休憩1h）',
                'workplace' => '福岡県福岡市',
                'display_price' => '950,000円',
                'skills' => 'Go, React, TypeScript, Node.js, AWS',
                'summary' => 'スタートアップ企業向けのクラウドネイティブアプリケーション開発プロジェクトです。コンテナ技術を活用したマイクロサービスアーキテクチャの採用と、CI/CDパイプラインの構築が含まれます。高可用性とスケーラビリティを重視した設計を行います。',
                'head_count' => '2名',
                'monthly_working_hours' => '160時間/月',
                'price' => bindec('10000000'), 
                'start' => bindec('1000000000'), 
                'area' => bindec('1000000000000000000000000000000000000000'), 
                'remote' => bindec('10'), 
                'frontend' => bindec('1000100'), 
                'backend' => bindec('10000'), 
                'framework' => bindec('110000000'), 
                'is_only_japanese' => false,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => 'SaaS型人事管理システムの開発',
                'period' => '10ヶ月〜（3月より）',
                'working_hours' => '9:00-18:00（休憩1h）',
                'workplace' => '神奈川県横浜市',
                'display_price' => '720,000円',
                'skills' => 'Ruby, Vue.js, TypeScript, Ruby on Rails, AWS',
                'summary' => '大手企業グループ向けの人事管理システム開発プロジェクトです。複数の子会社に対応可能なマルチテナント構造を採用し、人事データの統合管理や分析機能を実装します。グローバル展開を見据えた多言語対応も含まれます。',
                'head_count' => '3名',
                'monthly_working_hours' => '160時間/月',
                'price' => bindec('100000'), 
                'start' => bindec('100'), 
                'area' => bindec('10000000000000'), 
                'remote' => bindec('10'), 
                'frontend' => bindec('1000000'), 
                'backend' => bindec('100000000'), 
                'framework' => bindec('101000000000'), 
                'is_only_japanese' => false,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => '医療システム基盤再構築',
                'period' => '15ヶ月〜（8月より）',
                'working_hours' => '9:30-18:30（休憩1h）',
                'workplace' => '京都府京都市',
                'display_price' => '980,000円',
                'skills' => 'Java, Spring, TypeScript, Angular, Oracle',
                'summary' => '大規模医療機関向けの基幹システム再構築プロジェクトです。電子カルテシステムとの連携や、医療データの安全な管理・分析基盤の構築が主な目的です。高いセキュリティ要件と可用性が求められます。',
                'head_count' => '5名',
                'monthly_working_hours' => '165時間/月',
                'price' => bindec('10000000'), 
                'start' => bindec('10000000'), 
                'area' => bindec('10000000000000000000000000'), 
                'remote' => bindec('1'), 
                'frontend' => bindec('1000000'), 
                'backend' => bindec('100000'), 
                'framework' => bindec('10000000001'), 
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => 'IoTデバイス管理プラットフォーム構築',
                'period' => '7ヶ月〜（6月より）',
                'working_hours' => '9:00-17:30（休憩1h）',
                'workplace' => '北海道札幌市',
                'display_price' => '580,000円',
                'skills' => 'Python, Flask, TypeScript, React, AWS IoT',
                'summary' => '製造現場のIoTデバイスを統合管理するプラットフォームの構築プロジェクトです。リアルタイムデータの収集・分析、異常検知機能の実装が含まれます。寒冷地での特殊な環境要件にも対応します。',
                'head_count' => '2名',
                'monthly_working_hours' => '160時間/月',
                'price' => bindec('1000'), 
                'start' => bindec('100000'), 
                'area' => bindec('1'), 
                'remote' => bindec('10'), 
                'frontend' => bindec('1000000'), 
                'backend' => bindec('10000000'), 
                'framework' => bindec('100010000'), 
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => 'フィンテックアプリケーションの機能拡張',
                'period' => '9ヶ月〜（5月より）',
                'working_hours' => '9:30-18:30（休憩1h）',
                'workplace' => '福岡県福岡市',
                'display_price' => '820,000円',
                'skills' => 'Go, React, TypeScript, Node.js, Kubernetes',
                'summary' => '急成長中のフィンテック企業向けの決済プラットフォーム機能拡張プロジェクトです。ブロックチェーン技術の導入や、新たな決済手段への対応を行います。マイクロサービスアーキテクチャを採用し、決済処理の高速化と安定性向上を実現します。',
                'head_count' => '3名',
                'monthly_working_hours' => '160時間/月',
                'price' => bindec('1000000'), 
                'start' => bindec('10000'), 
                'area' => bindec('1000000000000000000000000000000000000000'), 
                'remote' => bindec('10'), 
                'frontend' => bindec('1000000'), 
                'backend' => bindec('10000'), 
                'framework' => bindec('110000000'), 
                'is_only_japanese' => false,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => '自治体向け行政システム刷新',
                'period' => '12ヶ月〜（2月より）',
                'working_hours' => '9:00-17:45（休憩1h）',
                'workplace' => '愛媛県松山市',
                'display_price' => '680,000円',
                'skills' => 'C#, ASP.NET MVC, TypeScript, Angular',
                'summary' => '地方自治体向けの行政システム刷新プロジェクトです。マイナンバー関連システムとの連携や、住民サービスのオンライン化対応が主な目的です。セキュリティ要件に準拠しつつ、使いやすいUIの実現を目指します。',
                'head_count' => '4名',
                'monthly_working_hours' => '155時間/月',
                'price' => bindec('10000'), 
                'start' => bindec('10'), 
                'area' => bindec('10000000000000000000000000000000000000'), 
                'remote' => bindec('1'), 
                'frontend' => bindec('1000000'), 
                'backend' => bindec('100'), 
                'framework' => bindec('11'), 
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => 'スマートファクトリー基盤システム開発',
                'period' => '11ヶ月〜（9月より）',
                'working_hours' => '9:00-18:00（休憩1h）',
                'workplace' => '茨城県つくば市',
                'display_price' => '920,000円',
                'skills' => 'Python, Java, React, Django, Spring',
                'summary' => '大手製造業向けのスマートファクトリー基盤システム開発プロジェクトです。IoTセンサーからのデータ収集・分析、AI による予知保全機能の実装が含まれます。製造現場のDX推進を担う重要案件です。',
                'head_count' => '3名',
                'monthly_working_hours' => '170時間/月',
                'price' => bindec('10000000'), 
                'start' => bindec('100000000'), 
                'area' => bindec('10000000'), 
                'remote' => bindec('10'), 
                'frontend' => bindec('1000100'), 
                'backend' => bindec('10100000'), 
                'framework' => bindec('10100000100'), 
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => '電力会社向けスマートメーター管理システム',
                'period' => '10ヶ月〜（11月より）',
                'working_hours' => '9:15-18:15（休憩1h）',
                'workplace' => '宮城県仙台市',
                'display_price' => '780,000円',
                'skills' => 'Java, Spring, TypeScript, Vue.js, AWS',
                'summary' => '大手電力会社向けのスマートメーター管理システム開発プロジェクトです。数百万台規模のIoTデバイスからのリアルタイムデータ収集と分析、電力使用量の予測分析機能の実装が含まれます。大規模データ処理基盤の構築も担当します。',
                'head_count' => '4名',
                'monthly_working_hours' => '165時間/月',
                'price' => bindec('100000'),
                'start' => bindec('10000000000'),
                'area' => bindec('1000'),
                'remote' => bindec('10'),
                'frontend' => bindec('1000000'),
                'backend' => bindec('100000'),
                'framework' => bindec('110000000000'),
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => '次世代モビリティサービスプラットフォーム',
                'period' => '8ヶ月〜（12月より）',
                'working_hours' => '10:00-19:00（休憩1h）',
                'workplace' => '広島県広島市',
                'display_price' => '880,000円',
                'skills' => 'Go, React, TypeScript, Node.js, GCP',
                'summary' => '自動運転技術を活用した次世代モビリティサービスのプラットフォーム開発プロジェクトです。リアルタイムな配車管理、経路最適化、利用者向けモバイルアプリケーションの開発が含まれます。位置情報処理やルート検索の高速化が重要な要件です。',
                'head_count' => '3名',
                'monthly_working_hours' => '160時間/月',
                'price' => bindec('1000000'),
                'start' => bindec('100000000000'),
                'area' => bindec('1000000000000000000000000000000000'),
                'remote' => bindec('10'),
                'frontend' => bindec('1000000'),
                'backend' => bindec('10000'),
                'framework' => bindec('110000000'),
                'is_only_japanese' => false,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ],
            [
                'title' => 'オンライン教育プラットフォーム開発',
                'period' => '6ヶ月〜（7月より）',
                'working_hours' => '9:30-18:30（休憩1h）',
                'workplace' => '兵庫県神戸市',
                'display_price' => '620,000円',
                'skills' => 'PHP, Laravel, Vue.js, TypeScript, AWS',
                'summary' => '教育機関向けのオンライン学習プラットフォーム開発プロジェクトです。ライブ配信機能、課題管理、進捗管理機能の実装が含まれます。また、学習分析機能やレコメンデーション機能の追加も予定しています。',
                'head_count' => '2名',
                'monthly_working_hours' => '160時間/月',
                'price' => bindec('10000'),
                'start' => bindec('1000000'),
                'area' => bindec('1000000000000000000000000000'),
                'remote' => bindec('10'),
                'frontend' => bindec('1000000'),
                'backend' => bindec('1000000'),
                'framework' => bindec('100001000000'),
                'is_only_japanese' => true,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24)),
                'updated_at' => now()->subDays(rand(1, 15))->subHours(rand(1, 12)),
            ]
        ];
        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}
