<?php

return [
    'greeting' => '挨拶',
    'manners' => 'マナー',
    'courtesy' => '礼儀',
    'honorific' => '敬語',
    'wording' => '言葉遣い',
    'humility' => '謙虚',
    'cooperation' => '協調性',
    'empathy' => '共感性',
    'work_attitude' => '勤務態度',
    'hospitality' => 'ホスピタリティー',
    'communication' => 'コミュニケーション',
    'presentation' => 'プレゼンテーション',
    'design_sense' => 'デザインセンス',
    'writing_skills' => '文章力',
    'expressiveness' => '表現力',
    'effort' => '努力',
    'overtime' => '残業',
    'active' => '能動的',
    'security_awareness' => 'セキュリティー意識',
    'leadership' => 'リーダーシップ',
    'management_skills' => 'マネジメント力',
    'problem_solving_ability' => '問題解決力',
    'independently' => '一人称で動ける',
    'spontaneous_action' => '自発的な行動',
    'webcam' => 'Webカメラ表示',
    'touch_typing' => 'ブラインドタッチ',
    'generative_ai' => '生成AI活用',
    'english_reading_writing' => '英語(読み書き)',
    'english_conversation' => '英語(会話)',
    'health' => '健康面'
];
