<?php

return [
    'items' => [
        'greeting' => '挨拶',
        'manners' => 'マナー',
        'etiquette' => '礼儀',
        'honorific' => '敬語',
        'wording' => '言葉遣い',
        'writing' => '文章力',
        'cooperation' => '協調性',
        'empathy' => '共感性',
        'attendance' => '勤怠',
        'attitude' => '勤務中態度',
        'security' => 'セキュリティー意識',
        'initiative' => '自発的な行動',
        'hospitality' => 'ホスピタリティー',
        'communication' => 'コミュニケーション',
        'presentation' => 'プレゼンテーション',
        'problem_solving' => '問題解決力',
        'leadership' => 'リーダーシップ',
        'management' => 'マネジメント力',
        'self_development' => '自己啓発',
        'patience' => '忍耐力',
        'responsibility' => '責任感',
        'stability' => '安定志向',
        'english_reading' => '英語力(読書)',
        'english_speaking' => '英語力(会話)',
        'word' => 'Word',
        'excel' => 'Excel',
        'powerpoint' => 'Power Point',
        'webcam' => 'Webカメラ表示',
        'ai_utilization' => '生成AI活用',
        'typing' => 'タイピング',
        'challenge' => 'チャレンジ精神',
        'positive' => 'ポジティブ',
        'health' => '健康面',
        'comprehension' => '理解力',
        'qa_clarity' => 'Ｑ＆Ａの明確さ'
    ],
    'ratings' => range(1, 10)
];
